### PR TITLE
Replace shell scripts with a Makefile

### PR DESCRIPTION
**Pull request by texadactyl**
Only compiles those source files which have actually changed.

### CODE REVIEW

**Comment by texadactyl** [comment]
Much better result!  Thank you, Evgeny.

**Comment by texadactyl** [comment]
Agreed.  I'll resubmit PR with an enhanced Makefile.

**Comment by smirik** [comment]
Btw there is no need to close PR. You can simply push & update this PR. That's the usual flow on github. Reopening it.

**Comment by smirik** [comment]
Do we need to keep executable files (.sh) anymore? Or could we simply remove them?

**Comment by texadactyl** [comment]
All done.  The intent is to use only the Makefile for all operations.  Try running `make` without any parameters for help.

**Comment by texadactyl** [comment]
By the way, I guessed as to what your intent was for managing the input files versus the sample input files!  (-:

**Comment by texadactyl** [comment]
How did I do, Ilya?

**Comment by smirik** [comment]
@texadactyl Could you please then also remove .sh files that are not needed anymore. After that, I think, we are good to merge.

**Comment by texadactyl** [comment]
Aye aye, sir!

**Comment by smirik** [comment]
Great work, guys! Merging.

**Pull request merged**
